#! /bin/sh

echo '<!doctype html>'
echo '<html>'
echo '<head>'
echo '<title>Project Euler</title>'
echo '<link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro" rel="stylesheet">'
echo '<link rel="stylesheet" href="style.css">'
echo '</head>'
echo '<body>'
echo '<h1>Project Euler</h1>'
for n in `ls src | grep '\.lhs' | cut -d '.' -f 1`; do
  echo '<div class="solution" id="'$n'">'
  echo '<div class="solution-title">'
  echo '<h2><a href="#'$n'"><span class="hash"># </span>'$n'</a></h2>'
  echo '<span class="statement"><a href="https://projecteuler.net/problem='$n'">[statement]</a></span>'
  echo '</div>'
  pandoc -f markdown+lhs -t html src/$n.lhs
  echo '</div>'
done
echo '</body>'
echo '</html>'
